const testData=  [
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    },
    {
        level: '',
        nameUp: '',
        nameDown: '',
        leadTime: '',
        duration: '',
        components: '',
        text: '',
        textDown: '',
        K: false,
        R: false,
        V: false,
        S: false,
        M: false
    }
]

export default testData;